#include "firmware/mc02/app/src/app.hpp"

#include <bdma.h>
#include <device/usbd.h>
#include <dma.h>
#include <fdcan.h>
#include <gpio.h>
#include <main.h>
#include <spi.h>
#include <tim.h>
#include <usart.h>

#include "firmware/mc02/app/src/can/can.hpp"
#include "firmware/mc02/app/src/diag/can_diag.hpp"
#include "firmware/mc02/app/src/diag/loop_profile.hpp"
#include "firmware/mc02/app/src/gpio/gpio.hpp"
#include "firmware/mc02/app/src/led/led.hpp"
#include "firmware/mc02/app/src/spi/bmi088/accel.hpp"
#include "firmware/mc02/app/src/spi/bmi088/gyro.hpp"
#include "firmware/mc02/app/src/spi/bmi088/service.hpp"
#include "firmware/mc02/app/src/spi/bmi088/temperature.hpp"
#include "firmware/mc02/app/src/timer/timer.hpp"
#include "firmware/mc02/app/src/uart/uart.hpp"
#include "firmware/mc02/app/src/usb/vendor.hpp"
#include "firmware/mc02/app/src/utility/boot_mailbox.hpp"
#include "firmware/mc02/app/src/utility/interrupt_lock.hpp"

int main() {
    SCB->VTOR = 0x08040000U;
    librmcs::firmware::app.init().run();
}

namespace librmcs::firmware {

// Linker-defined bounds of the .itcm section: load image in FLASH (_siitcm) and
// run location in ITCM (_sitcm.._eitcm). extern "C" so they bind to the global
// linker symbols instead of namespaced C++ symbols.
// NOLINTBEGIN(readability-identifier-naming): these names are fixed by
// bsp/linker/STM32H723VGTx_APP.ld, so the repository's naming convention cannot
// apply -- renaming them here would just fail to link.
extern "C" {
extern uint32_t _siitcm, _sitcm, _eitcm;
extern uint32_t _sidtcm, _sdtcm, _edtcm;
extern uint32_t _sid2sram, _sd2sram, _ed2sram;
}
// NOLINTEND(readability-identifier-naming)

namespace {

// Make the D2 SRAM range that holds the UART port objects non-cacheable, the way
// MPU_Config() already does for the first 32 KB of AXI SRAM.
//
// 0x30000000 falls inside the Cortex-M7 default map's SRAM region, which is
// Normal write-back write-allocate -- cacheable. Leaving it that way would put
// the DMA rings behind the D-cache: the core would read stale bytes for data the
// DMA had written, and the DMA would read stale bytes for data the core had
// written but not cleaned. Attributes match region 0 (TEX level 1, C=0, B=0 =>
// Normal, non-cacheable), minus instruction fetch, which nothing does here.
//
// Runs after MX_MPU_Config() rather than inside it: MPU_Config lives in
// bsp/cubemx/Core/Src/main.c and is regenerated by CubeMX. Region 0 is the only
// region that file configures, so region 1 is free.
void configure_d2_sram_mpu_region() {
    MPU_Region_InitTypeDef region = {};
    region.Enable = MPU_REGION_ENABLE;
    region.Number = MPU_REGION_NUMBER1;
    region.BaseAddress = 0x30000000U;
    region.Size = MPU_REGION_SIZE_32KB;
    region.SubRegionDisable = 0x00;
    region.TypeExtField = MPU_TEX_LEVEL1;
    region.AccessPermission = MPU_REGION_FULL_ACCESS;
    region.DisableExec = MPU_INSTRUCTION_ACCESS_DISABLE;
    region.IsShareable = MPU_ACCESS_NOT_SHAREABLE;
    region.IsCacheable = MPU_ACCESS_NOT_CACHEABLE;
    region.IsBufferable = MPU_ACCESS_NOT_BUFFERABLE;

    HAL_MPU_Disable();
    HAL_MPU_ConfigRegion(&region);
    HAL_MPU_Enable(MPU_HFNMI_PRIVDEF);
}

} // namespace

App::App() {
    const utility::InterruptLockGuard guard;

    // Copy the latency-critical CAN forwarding code (the .itcm section) into
    // zero-wait ITCM before anything can call it. app.cpp replaces the CubeMX
    // main(), so this stands in for the startup .data-style copy loop. Done with
    // caches still off, so the writes reach ITCM directly; DSB/ISB then make the
    // new instructions visible to the fetch unit.
    for (uint32_t *dst = &_sitcm, *src = &_siitcm; dst < &_eitcm;)
        *dst++ = *src++;
    // Hot forwarding data (serializer + USB batches + CAN objects) into DTCM, so
    // the uplink ISR touches no AXI bus. Must run before usb/can init below.
    for (uint32_t *dst = &_sdtcm, *src = &_sidtcm; dst < &_edtcm;)
        *dst++ = *src++;

    // The four UART port objects and their DMA rings into D2 SRAM, next to the
    // DMA1 streams that drive them (see uart.hpp and the .d2_sram section in the
    // linker script). The clocks come first: RCC_AHB2ENR resets with the D2 SRAM
    // enables clear on this part, so the copy below would otherwise write into a
    // memory whose clock is gated. Doing it here, with the caches still off, also
    // means the copy lands in memory directly -- configure_d2_sram_mpu_region()
    // has not run yet, so the range is still cacheable by the default map.
    // SRAM1 and SRAM2 only: the H723 splits its 32 KB of D2 SRAM into those two
    // 16 KB banks and has no SRAM3, so __HAL_RCC_D2SRAM3_CLK_ENABLE does not
    // exist here (stm32h723xx.h defines RCC_AHB2ENR_D2SRAM1EN/2EN and no 3EN).
    __HAL_RCC_D2SRAM1_CLK_ENABLE();
    __HAL_RCC_D2SRAM2_CLK_ENABLE();
    for (uint32_t *dst = &_sd2sram, *src = &_sid2sram; dst < &_ed2sram;)
        *dst++ = *src++;

    __DSB();
    __ISB();

    // Wrapper around the generated MPU_Config(), defined in main.c's
    // USER CODE BEGIN 4. CubeMX regenerates MPU_Config's prototype as `static`
    // outside any USER CODE block, so it cannot be declared in main.h directly;
    // see the comment on librmcs_mpu_config in main.h.
    librmcs_mpu_config();
    configure_d2_sram_mpu_region();
    SCB_EnableICache();
    SCB_EnableDCache();
    HAL_Init();
    SystemClock_Config();
    // Enables PLL2 (80 MHz) as the FDCAN kernel clock for the 1 Mbit/s
    // arbitration + 5 Mbit/s CAN-FD data phase, and PLL3 (96 MHz) as the kernel
    // clock for the USART2/3/4/5/7/8 group -- 96 MHz divides exactly into 4.8 M,
    // 4 M, 2 M and 100 k, so every baudrate those ports run lands on an integer
    // BRR with zero error. Generated from the .ioc; must be called here since
    // app.cpp replaces the CubeMX main().
    PeriphCommonClock_Config();

    utility::boot_mailbox.clear();

    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;

    RCC_PeriphCLKInitTypeDef usb_clk = {};
    usb_clk.PeriphClockSelection = RCC_PERIPHCLK_USB;
    usb_clk.UsbClockSelection = RCC_USBCLKSOURCE_HSI48;
    if (HAL_RCCEx_PeriphCLKConfig(&usb_clk) != HAL_OK)
        Error_Handler();
    HAL_PWREx_EnableUSBVoltageDetector();
    __HAL_RCC_USB_OTG_HS_CLK_ENABLE();

    // Trim HSI48 against the host's start-of-frame packets. The USB clock above
    // is the free-running HSI48, and DS13313 Table 35 gives its accuracy as
    // ACCHSI48_REL = -4.5% .. +3.5% over TJ = -40..125 C (47.5..48.5 MHz even at
    // room temperature). USB 2.0 full speed allows +-0.25%, so the raw oscillator
    // is out of specification by more than an order of magnitude once the board
    // heats up -- it only enumerates reliably on the bench because the factory
    // trim is centred near 25 C. The Clock Recovery System locks HSI48 to the
    // 1 kHz SOF and pulls it to the host's accuracy, which is what makes HSI48
    // usable as a USB clock at all.
    //
    // STM32F407 has neither HSI48 nor CRS; c_board derives its USB clock from
    // the crystal-fed PLL, so it is accurate by construction and has nothing to
    // recover. Sync source USB1: the H723 exposes a single OTG_HS instance,
    // enabled just above.
    __HAL_RCC_CRS_CLK_ENABLE();
    RCC_CRSInitTypeDef crs_init = {};
    crs_init.Prescaler = RCC_CRS_SYNC_DIV1;
    crs_init.Source = RCC_CRS_SYNC_SOURCE_USB1;
    crs_init.Polarity = RCC_CRS_SYNC_POLARITY_RISING;
    // 48 MHz counted over one 1 kHz SOF period, minus one.
    crs_init.ReloadValue = __HAL_RCC_CRS_RELOADVALUE_CALCULATE(48000000U, 1000U);
    crs_init.ErrorLimitValue = RCC_CRS_ERRORLIMIT_DEFAULT;
    crs_init.HSI48CalibrationValue = RCC_CRS_HSI48CALIBRATION_DEFAULT;
    HAL_RCCEx_CRSConfig(&crs_init);

    MX_GPIO_Init();
    MX_DMA_Init();
    // BDMA is the only DMA controller that reaches SPI6 (D3 domain), so the
    // WS2812 LED depends on it. CubeMX emits its clock enable and NVIC setup in
    // a file of its own, bdma.c, rather than in MX_DMA_Init() -- and app.cpp
    // replaces the generated main(), so the call has to be made here. Must
    // precede MX_SPI6_Init(), whose MspInit runs HAL_DMA_Init() on
    // BDMA_Channel0: with the clock still gated those register writes are
    // dropped, HAL_SPI_Transmit_DMA() then reports HAL_OK for a transfer that
    // never starts, and hspi6 stays BUSY_TX forever with the LED dark.
    MX_BDMA_Init();
    MX_FDCAN1_Init();
    MX_USART10_UART_Init();
    MX_UART7_Init();
    MX_USART1_UART_Init();
    MX_FDCAN2_Init();
    MX_FDCAN3_Init();
    MX_SPI6_Init();
#ifdef LIBRMCS_APP_IMU_ENABLE
    MX_SPI2_Init();
#endif
    MX_UART5_Init();
#if defined(LIBRMCS_APP_RS485_ENABLE) && LIBRMCS_APP_RS485_ENABLE
    // The two RS-485 ports. Both MX_*_Init functions also run HAL_RS485Ex_Init,
    // which is what turns CR3.DEM on. Left out of the default build because the
    // pair costs 11 KB of the 32 KB D2 SRAM region -- see uart.hpp.
    MX_USART2_UART_Init();
    MX_USART3_UART_Init();
#endif
    MX_TIM1_Init();
    MX_TIM2_Init();
    MX_TIM5_Init();

    // Start the quarter-microsecond timestamp source before anything that stamps
    // events (UART tx timeouts, IMU data-ready EXTI, SPI uplinks).
    timer::timer.init();

    led::led.init();
    gpio::gpio.init();
    usb::vendor.init();
    can::can1.init();
    can::can2.init();
    can::can3.init();
    uart::uart1.init();
    uart::uart2.init();
    uart::uart3.init();
    uart::uart_dbus.init();
#if defined(LIBRMCS_APP_RS485_ENABLE) && LIBRMCS_APP_RS485_ENABLE
    uart::uart0.init();
    uart::uart4.init();
#endif
#ifdef LIBRMCS_APP_IMU_ENABLE
    spi::bmi088::accelerometer.init();
    spi::bmi088::gyroscope.init();
    spi::bmi088::temperature.init();
#endif
}

// NOLINTNEXTLINE(readability-convert-member-functions-to-static)
[[noreturn]] void App::run() {
    while (true) {
        diag::note_main_loop();

#if defined(LIBRMCS_APP_LOOP_BALLAST_CYCLES) && LIBRMCS_APP_LOOP_BALLAST_CYCLES
        // Measurement instrument, never shipped: lengthens the main-loop period
        // by a known number of DWT cycles (550 per microsecond at 550 MHz) so
        // that throughput can be plotted against loop period.
        //
        // This is the only way to tell the two candidate bottlenecks apart. If
        // packet rate tracks the ballast, the loop is on the critical path and
        // code placement, memory ordering and atomics are worth optimising. If
        // it does not move, the ceiling belongs to host scheduling and every
        // board-side optimisation is unfalsifiable until that changes.
        //
        // Deliberately a busy-wait rather than a sleep: the point is to occupy
        // the CPU exactly as real work would, leaving interrupts free to run.
        {
            const std::uint32_t ballast_start = DWT->CYCCNT;
            while ((DWT->CYCCNT - ballast_start) < (LIBRMCS_APP_LOOP_BALLAST_CYCLES)) {}
        }
#endif

        diag::profile::mark(diag::profile::Section::kTudTask);
        tud_task();

        // Once per pass, not once per try_transmit() call; see Vendor::poll_session.
        usb::vendor->poll_session();
        usb::poll_dfu_runtime_reboot();

        // CAN telemetry (LIBRMCS_APP_CAN_DIAG builds only); paces itself off the
        // timer, so calling it every pass costs one timer read when disarmed and
        // compiles to nothing when the switch is off.
        diag::profile::mark(diag::profile::Section::kOther);
        diag::poll();

        diag::profile::mark(diag::profile::Section::kGpio);
        gpio::gpio->poll_periodic_input_samples();

#ifdef LIBRMCS_APP_IMU_ENABLE
        // Promote a due temperature probe to pending, then service at most one
        // BMI088 SPI read (gyro > accel > temperature) per iteration.
        diag::profile::mark(diag::profile::Section::kImu);
        spi::bmi088::temperature->poll_pending_probe();
        spi::bmi088::service_pending_reads();
#endif

        // LED animation; non-blocking unless colour changes (one SPI frame per
        // change, ~330 us at the WS2812 bit rate). Polled here so no ISR context
        // ever touches SPI. The state reported is the host session (nonce
        // handshake plus keepalive lease), not mere USB enumeration, so steady
        // green means data is actually being forwarded.
        diag::profile::mark(diag::profile::Section::kLed);
        led::led->set_host_connected(usb::vendor->session_established());
        led::led->poll();

        // The seven usb->try_transmit() calls are interleaved on purpose: a batch
        // filled by CAN1 starts moving toward the endpoint before UART1 is even
        // looked at. The profiler charges all seven to kUsb and each source to
        // its own section, so their relative cost is visible rather than assumed.
        diag::profile::mark(diag::profile::Section::kUsb);
        usb::vendor->try_transmit();
        diag::profile::mark(diag::profile::Section::kCan);
        can::can1->try_transmit();
        diag::profile::mark(diag::profile::Section::kUsb);
        usb::vendor->try_transmit();
        diag::profile::mark(diag::profile::Section::kCan);
        can::can2->try_transmit();
        diag::profile::mark(diag::profile::Section::kUsb);
        usb::vendor->try_transmit();
        diag::profile::mark(diag::profile::Section::kCan);
        can::can3->try_transmit();
        diag::profile::mark(diag::profile::Section::kUsb);
        usb::vendor->try_transmit();
        diag::profile::mark(diag::profile::Section::kUart);
        uart::uart1->try_transmit();
        diag::profile::mark(diag::profile::Section::kUsb);
        usb::vendor->try_transmit();
        diag::profile::mark(diag::profile::Section::kUart);
        uart::uart2->try_transmit();
        diag::profile::mark(diag::profile::Section::kUsb);
        usb::vendor->try_transmit();
        diag::profile::mark(diag::profile::Section::kUart);
        uart::uart3->try_transmit();
        diag::profile::mark(diag::profile::Section::kUsb);
        usb::vendor->try_transmit();
        diag::profile::mark(diag::profile::Section::kUart);
        uart::uart_dbus->try_transmit();
#if defined(LIBRMCS_APP_RS485_ENABLE) && LIBRMCS_APP_RS485_ENABLE
        usb::vendor->try_transmit();
        uart::uart0->try_transmit();
        usb::vendor->try_transmit();
        uart::uart4->try_transmit();
#endif

        diag::profile::end_pass();
    }
}

} // namespace librmcs::firmware
