name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    container:
      image: ${{ vars.DOCKERHUB_USERNAME }}/librmcs-ci:latest
      credentials:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Configure git safe.directory
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Run clang-format check
        run: .scripts/clang-format-check

      - name: Configure host
        run: cmake --preset linux-debug -S host

      - name: Build host
        run: cmake --build host/build

      - name: Configure firmware/rmcs_board
        run: cmake --preset debug -S firmware/rmcs_board

      - name: Build firmware/rmcs_board
        run: cmake --build firmware/rmcs_board/build

      - name: Configure firmware/c_board
        run: cmake --preset debug -S firmware/c_board

      - name: Build firmware/c_board
        run: cmake --build firmware/c_board/build --target c_board_app c_board_bootloader

      - name: Run clang-tidy check
        run: .scripts/clang-tidy-check
